/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/VXh597jvjjm
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Link } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { useState } from "react";

export default function Sidebar() {
    const [isSidebarCollapsed, setIsSidebarCollapsed] = useState(false);
    return (
        <>
            <div className="flex h-screen bg-background">
                <div
                    className={`space-y-2
                 hidden h-full flex-col border-r bg-background md:flex ${
                     isSidebarCollapsed ? "w-16" : "w-64"
                 }`}
                >
                    <div className="flex h-16 items-center justify-between border-b px-4">
                        <Link
                            href="#"
                            className="flex items-center gap-2 font-bold"
                            prefetch={false}
                        >
                            {/* <MountainIcon className="h-6 w-6" /> */}
                            <span
                                className={`${
                                    isSidebarCollapsed ? "hidden" : "block"
                                }`}
                            >
                                IMS
                            </span>
                        </Link>
                        <Button
                            variant="ghost"
                            size="icon"
                            onClick={() =>
                                setIsSidebarCollapsed(!isSidebarCollapsed)
                            }
                        >
                            <MenuIcon className="h-5 w-5" />
                            <span className="sr-only">Toggle sidebar</span>
                        </Button>
                    </div>
                    <div
                        className={`flex-1 overflow-auto py-4 ${
                            isSidebarCollapsed ? "px-2" : "px-4"
                        }`}
                    >
                        <nav className="space-y-2">
                            {/* <div
                                className={`text-xs font-medium uppercase text-muted-foreground ${
                                    isSidebarCollapsed ? "hidden" : "block"
                                }`}
                            >
                                General
                            </div> */}
                            <Link
                                href="#"
                                className={`flex items-center gap-2 rounded-md px-3 py-2 text-sm font-medium transition-colors hover:bg-muted hover:text-foreground ${
                                    isSidebarCollapsed ? "justify-center" : ""
                                }`}
                                prefetch={false}
                            >
                                <HomeIcon className="h-5 w-5" />
                                <span
                                    className={`${
                                        isSidebarCollapsed ? "hidden" : "block"
                                    }`}
                                >
                                    Home
                                </span>
                            </Link>
                            <Link
                                href="#"
                                className={`flex items-center gap-2 rounded-md px-3 py-2 text-sm font-medium transition-colors hover:bg-muted hover:text-foreground ${
                                    isSidebarCollapsed ? "justify-center" : ""
                                }`}
                                prefetch={false}
                            >
                                <LayoutDashboardIcon className="h-5 w-5" />
                                <span
                                    className={`${
                                        isSidebarCollapsed ? "hidden" : "block"
                                    }`}
                                >
                                    Dashboard
                                </span>
                            </Link>
                            {/* <div
                                className={`text-xs font-medium uppercase text-muted-foreground ${
                                    isSidebarCollapsed ? "hidden" : "block"
                                }`}
                            >
                                Ecommerce
                            </div> */}
                            <Link
                                href="#"
                                className={`flex items-center gap-2 rounded-md px-3 py-2 text-sm font-medium transition-colors hover:bg-muted hover:text-foreground ${
                                    isSidebarCollapsed ? "justify-center" : ""
                                }`}
                                prefetch={false}
                            >
                                <PackageIcon className="h-5 w-5" />
                                <span
                                    className={`${
                                        isSidebarCollapsed ? "hidden" : "block"
                                    }`}
                                >
                                    Products
                                </span>
                            </Link>
                            <Link
                                href="#"
                                className={`flex items-center gap-2 rounded-md px-3 py-2 text-sm font-medium transition-colors hover:bg-muted hover:text-foreground ${
                                    isSidebarCollapsed ? "justify-center" : ""
                                }`}
                                prefetch={false}
                            >
                                <ShoppingCartIcon className="h-5 w-5" />
                                <span
                                    className={`${
                                        isSidebarCollapsed ? "hidden" : "block"
                                    }`}
                                >
                                    Orders
                                </span>
                            </Link>
                            <Link
                                href="#"
                                className={`flex items-center gap-2 rounded-md px-3 py-2 text-sm font-medium transition-colors hover:bg-muted hover:text-foreground ${
                                    isSidebarCollapsed ? "justify-center" : ""
                                }`}
                                prefetch={false}
                            >
                                <UsersIcon className="h-5 w-5" />
                                <span
                                    className={`${
                                        isSidebarCollapsed ? "hidden" : "block"
                                    }`}
                                >
                                    Customers
                                </span>
                            </Link>
                            {/* <div
                                className={`text-xs font-medium uppercase text-muted-foreground ${
                                    isSidebarCollapsed ? "hidden" : "block"
                                }`}
                            >
                                Analytics
                            </div> */}
                            <Link
                                href="#"
                                className={`flex items-center gap-2 rounded-md px-3 py-2 text-sm font-medium transition-colors hover:bg-muted hover:text-foreground ${
                                    isSidebarCollapsed ? "justify-center" : ""
                                }`}
                                prefetch={false}
                            >
                                <LineChartIcon className="h-5 w-5" />
                                <span
                                    className={`${
                                        isSidebarCollapsed ? "hidden" : "block"
                                    }`}
                                >
                                    Analytics
                                </span>
                            </Link>
                            <Link
                                href="#"
                                className={`flex items-center gap-2 rounded-md px-3 py-2 text-sm font-medium transition-colors hover:bg-muted hover:text-foreground ${
                                    isSidebarCollapsed ? "justify-center" : ""
                                }`}
                                prefetch={false}
                            >
                                <BarChartIcon className="h-5 w-5" />
                                <span
                                    className={`${
                                        isSidebarCollapsed ? "hidden" : "block"
                                    }`}
                                >
                                    Reports
                                </span>
                            </Link>
                        </nav>
                    </div>
                </div>
                <main className="flex-1 p-8">
                    <h1 className="text-3xl font-bold">
                        Welcome to the Dashboard
                    </h1>
                    <p className="mt-4 text-muted-foreground">
                        This is where you can manage your projects, team, and
                        settings.
                    </p>
                </main>
            </div>
        </>
    );
}

function BriefcaseIcon(props) {
    return (
        <svg
            {...props}
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
        >
            <path d="M16 20V4a2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v16" />
            <rect width="20" height="14" x="2" y="6" rx="2" />
        </svg>
    );
}

function HomeIcon(props) {
    return (
        <svg
            {...props}
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
        >
            <path d="m3 9 9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z" />
            <polyline points="9 22 9 12 15 12 15 22" />
        </svg>
    );
}

function LayoutGridIcon(props) {
    return (
        <svg
            {...props}
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
        >
            <rect width="7" height="7" x="3" y="3" rx="1" />
            <rect width="7" height="7" x="14" y="3" rx="1" />
            <rect width="7" height="7" x="14" y="14" rx="1" />
            <rect width="7" height="7" x="3" y="14" rx="1" />
        </svg>
    );
}

function LogOutIcon(props) {
    return (
        <svg
            {...props}
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
        >
            <path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4" />
            <polyline points="16 17 21 12 16 7" />
            <line x1="21" x2="9" y1="12" y2="12" />
        </svg>
    );
}

function MountainIcon(props) {
    return (
        <svg
            {...props}
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
        >
            <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
        </svg>
    );
}

function SettingsIcon(props) {
    return (
        <svg
            {...props}
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
        >
            <path d="M12.22 2h-.44a2 2 0 0 0-2 2v.18a2 2 0 0 1-1 1.73l-.43.25a2 2 0 0 1-2 0l-.15-.08a2 2 0 0 0-2.73.73l-.22.38a2 2 0 0 0 .73 2.73l.15.1a2 2 0 0 1 1 1.72v.51a2 2 0 0 1-1 1.74l-.15.09a2 2 0 0 0-.73 2.73l.22.38a2 2 0 0 0 2.73.73l.15-.08a2 2 0 0 1 2 0l.43.25a2 2 0 0 1 1 1.73V20a2 2 0 0 0 2 2h.44a2 2 0 0 0 2-2v-.18a2 2 0 0 1 1-1.73l.43-.25a2 2 0 0 1 2 0l.15.08a2 2 0 0 0 2.73-.73l.22-.39a2 2 0 0 0-.73-2.73l-.15-.08a2 2 0 0 1-1-1.74v-.5a2 2 0 0 1 1-1.74l.15-.09a2 2 0 0 0 .73-2.73l-.22-.38a2 2 0 0 0-2.73-.73l-.15.08a2 2 0 0 1-2 0l-.43-.25a2 2 0 0 1-1-1.73V4a2 2 0 0 0-2-2z" />
            <circle cx="12" cy="12" r="3" />
        </svg>
    );
}

function UsersIcon(props) {
    return (
        <svg
            {...props}
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
        >
            <path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2" />
            <circle cx="9" cy="7" r="4" />
            <path d="M22 21v-2a4 4 0 0 0-3-3.87" />
            <path d="M16 3.13a4 4 0 0 1 0 7.75" />
        </svg>
    );
}

function MenuIcon(props) {
    return (
        <svg
            {...props}
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
        >
            <line x1="4" x2="20" y1="12" y2="12" />
            <line x1="4" x2="20" y1="6" y2="6" />
            <line x1="4" x2="20" y1="18" y2="18" />
        </svg>
    );
}

function LayoutDashboardIcon(props) {
    return (
        <svg
            {...props}
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
        >
            <rect width="7" height="9" x="3" y="3" rx="1" />
            <rect width="7" height="5" x="14" y="3" rx="1" />
            <rect width="7" height="9" x="14" y="12" rx="1" />
            <rect width="7" height="5" x="3" y="16" rx="1" />
        </svg>
    );
}

function PackageIcon(props) {
    return (
        <svg
            {...props}
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
        >
            <path d="m7.5 4.27 9 5.15" />
            <path d="M21 8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16Z" />
            <path d="m3.3 7 8.7 5 8.7-5" />
            <path d="M12 22V12" />
        </svg>
    );
}

function ShoppingCartIcon(props) {
    return (
        <svg
            {...props}
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
        >
            <circle cx="8" cy="21" r="1" />
            <circle cx="19" cy="21" r="1" />
            <path d="M2.05 2.05h2l2.66 12.42a2 2 0 0 0 2 1.58h9.78a2 2 0 0 0 1.95-1.57l1.65-7.43H5.12" />
        </svg>
    );
}

function LineChartIcon(props) {
    return (
        <svg
            {...props}
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
        >
            <path d="M3 3v18h18" />
            <path d="m19 9-5 5-4-4-3 3" />
        </svg>
    );
}

function BarChartIcon(props) {
    return (
        <svg
            {...props}
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
        >
            <line x1="12" x2="12" y1="20" y2="10" />
            <line x1="18" x2="18" y1="20" y2="4" />
            <line x1="6" x2="6" y1="20" y2="16" />
        </svg>
    );
}
